import nav from "./modules/nav.js"
import changeLang from "./modules/change-lang.js"
import animation from "./modules/animation-line.js"
import swiper from "./modules/swiper.js"
import accordion from "./modules/accordion.js"
import form from "./modules/form.js"
import date from "./modules/date.js"


// import burger from "./modules/burger.js"
// import popup from "./modules/popup.js"
// import regularExpressions from "./modules/regularExpressions.js"
// import accordion from "./modules/accordion.js"
// import swiper from "./modules/swiper.js"
// import products from "./modules/products.js"