import nav from "./modules/nav.js"
import projects from "./modules/projects.js"
// import changeLang from "./modules/change-lang.js"
import animation from "./modules/animation-line.js"
import swiper from "./modules/swiper.js"
import accordion from "./modules/accordion.js"
import form from "./modules/form.js"
import date from "./modules/date.js"